[package]
name = "xdg-dirs-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
serial_test = { version = "3.2.0", default-features = false }
thiserror = "2.0.12"

[dev-dependencies]
serial_test = "3.2.0"
