[package]
name = "xdg-dirs"
version = "0.1.3"
edition = "2024"

[dependencies]
serial_test = { version = "3.2.0", default-features = false }
thiserror = "2.0.12"

[dev-dependencies]
serial_test = "3.2.0"
tempfile = "3.20.0"
